server:
  port: 8080

spring:
  application:
    name: cloud-order-server
  #consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

